version: '3.9'
services:
  go:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store:
